version: 0.2
phases:

  install:
    runtime-versions:
      python: 3.11
    commands: 
    
      - echo WebHook Event = $CODEBUILD_WEBHOOK_EVENT 
      - SOURCE_VERSION=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

      - pip3 install yamllint
      
  pre_build:
    commands:
      
      - echo "entered into pre build"
      - #echo `aws codebuild import-source-credentials --generate-cli-skeleton` >> import-source-credentials.json
      - aws codebuild import-source-credentials --cli-input-json file://import-source-credentials.json
      - git config --global credential.helper 'cache --timeout=3600'
 
  build:
    commands:

      - ls -litrh
      - pwd
      - git status
      - git branch
      - git log --oneline
      - git tag -l
      
      - git config --global user.email "purushotama.chintanippu@gmail.com"
      - git config --global user.name "purushotama21"
      - git remote -v
      - git remote set-url origin https://purushotama21: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@github.com/purushotama21/DevOpsDemos.git
      - git tag -a "test" -m "this is test tag"
      - git tag -l
      - git push origin test
